include:
  - board: nice_nano_v2
    shield: Lily58_L
    artifact-name: Lily58_left
  - board: nice_nano_v2
    shield: Lily58_R
    artifact-name: Lily58_right
  - board: nice_nano_v2
    shield: settings_reset