"""
Devicetree (.keymap) formatter for ZMK.

Outputs keymaps in ZMK's devicetree format with proper includes and formatting.
"""

from typing import Dict, Any, List


class DevicetreeFormatter:
    """
    Formatter for ZMK devicetree (.keymap) format.

    Produces output compatible with ZMK's keymap binding syntax.
    """

    def format(self, keymap: Dict[str, Any]) -> str:
        """
        Format keymap as devicetree .keymap file.

        Args:
            keymap: Keymap dictionary with layers and bindings

        Returns:
            Devicetree formatted string
        """
        lines = []

        # Header comment
        lines.append("/*")
        lines.append(" * ZMK Keymap")
        lines.append(" * Generated by zmk-studio")
        lines.append(" * ")
        lines.append(" * Extracted from keyboard via ZMK Studio protocol")
        lines.append(" */")
        lines.append("")

        # Standard includes
        lines.append("#include <behaviors.dtsi>")
        lines.append("#include <dt-bindings/zmk/keys.h>")
        lines.append("#include <dt-bindings/zmk/bt.h>")
        lines.append("")
        lines.append("/ {")
        lines.append("\tkeymap {")
        lines.append('\t\tcompatible = "zmk,keymap";')
        lines.append("")

        # Generate layers
        for layer in keymap.get("layers", []):
            layer_id = layer.get("id", 0)
            layer_name = layer.get("name", f"layer_{layer_id}")
            bindings = layer.get("bindings", [])

            lines.append(f"\t\t{layer_name}_layer {{")
            lines.append(f"\t\t\tbindings = <")

            # Format bindings in groups of 6 per line for readability (standard Lily58 layout)
            # Lily58 has 6 columns per side
            all_bindings = []
            for b in bindings:
                all_bindings.append(self._format_binding(b))

            # Write bindings with proper indentation
            # Standard layout: 6 keys left side, space, 6 keys right side = 12 keys per row
            rows = []
            for i in range(0, len(all_bindings), 12):
                row_left = all_bindings[i : i + 6]
                row_right = (
                    all_bindings[i + 6 : i + 12] if i + 6 < len(all_bindings) else []
                )
                row_str = "    " + "    ".join(row_left)
                if row_right:
                    row_str += "                         " + "    ".join(row_right)
                rows.append("\t\t\t\t" + row_str)

            lines.append("\n".join(rows))
            lines.append("\t\t\t>;")
            lines.append("\t\t};")
            lines.append("")

        lines.append("\t};")
        lines.append("};")
        lines.append("")

        return "\n".join(lines)

    def _format_binding(self, binding: Dict[str, Any]) -> str:
        """
        Format a single binding for devicetree.

        Args:
            binding: Binding dictionary with behavior_id, param1, param2

        Returns:
            Devicetree binding string
        """
        behavior_id = binding.get("behavior_id", 0)
        param1 = binding.get("param1", 0)
        param2 = binding.get("param2", 0)

        # Import here to avoid circular dependency
        from zmk_studio.mapping import BehaviorResolver

        resolver = BehaviorResolver()
        behavior_name = resolver.resolve(behavior_id)

        # Format parameters based on behavior
        if behavior_name == "kp":
            # Key press: &kp KEY
            from zmk_studio.mapping.keycodes import keycode_to_name, KEYCODE_BASE

            # Use keycode_to_name which handles all formats
            key_name = keycode_to_name(param1)
            return f"&kp {key_name}"

        elif behavior_name == "mo":
            # Momentary layer: &mo LAYER
            return f"&mo {param1}"

        elif behavior_name == "lt":
            # Layer-tap: &lt LAYER KEY
            from zmk_studio.mapping.keycodes import keycode_to_name, KEYCODE_BASE

            if param2 < KEYCODE_BASE:
                key_name = keycode_to_name(param2 + KEYCODE_BASE).replace("kp ", "")
            else:
                key_name = keycode_to_name(param2).replace("kp ", "")
            return f"&lt {param1} {key_name}"

        elif behavior_name == "mt":
            # Mod-tap: &mt MOD KEY
            from zmk_studio.mapping.modifiers import format_modifiers_from_bitmask
            from zmk_studio.mapping.keycodes import keycode_to_name, KEYCODE_BASE

            mod_str = format_modifiers_from_bitmask(param1)
            if param2 < KEYCODE_BASE:
                key_name = keycode_to_name(param2 + KEYCODE_BASE).replace("kp ", "")
            else:
                key_name = keycode_to_name(param2).replace("kp ", "")
            return f"&mt {mod_str} {key_name}"

        elif behavior_name == "to":
            # To layer: &to LAYER
            return f"&to {param1}"

        elif behavior_name == "tog":
            # Toggle layer: &tog LAYER
            return f"&tog {param1}"

        elif behavior_name == "trans":
            # Transparent: &trans
            return "&trans"

        elif behavior_name == "none":
            # None: &none
            return "&none"

        elif behavior_name == "bt":
            # Bluetooth behavior: &bt BT_SEL param1 or &bt BT_CLR
            if param1 == 0 and param2 == 0:
                return "&bt BT_CLR"
            return f"&bt BT_SEL {param2}"

        elif behavior_name == "rgb_ug":
            # RGB Underglow: &rgb_ug param1 param2
            return f"&rgb_ug {param1} {param2}"

        elif behavior_name == "ext_power":
            # External power: &ext_power param1 param2
            return f"&ext_power {param1} {param2}"

        elif behavior_name == "kt":
            # Key-tap: &kt KEY (key tap behavior)
            from zmk_studio.mapping.keycodes import keycode_to_name, KEYCODE_BASE
            from zmk_studio.mapping.keycodes import CONSUMER_KEYCODES

            # Handle consumer keys
            if param1 >= 0x00C00 and param1 < 0x01000:
                consumer_usage = param1 - 0x00C00
                consumer_name = CONSUMER_KEYCODES.get(
                    consumer_usage, f"C(0x{param1:04X})"
                )
                return f"&kt {consumer_name}"

            if param1 < KEYCODE_BASE:
                key_name = keycode_to_name(param1 + KEYCODE_BASE).replace("kp ", "")
            else:
                key_name = keycode_to_name(param1).replace("kp ", "")
            return f"&kt {key_name}"

        else:
            # Unknown behavior: &behavior param1 param2
            return f"&{behavior_name} {param1} {param2}"

    def get_extension(self) -> str:
        """Get file extension for devicetree format."""
        return ".keymap"


def format_modifiers_from_bitmask(bitmask: int) -> str:
    """
    Format modifier bitmask to ZMK modifier names.

    Args:
        bitmask: Modifier bitmask (8-bit)

    Returns:
        Space-separated modifier names

    Example:
        >>> format_modifiers_from_bitmask(0x03)
        'LCTRL LSHFT'
        >>> format_modifiers_from_bitmask(0x01)
        'LCTRL'
        >>> format_modifiers_from_bitmask(0x00)
        ''
    """
    from zmk_studio.mapping.modifiers import decode_modifiers, format_modifiers

    modifiers = decode_modifiers(bitmask)
    return format_modifiers(modifiers, nested=True)


__all__ = ["DevicetreeFormatter"]
