metadata:
  timestamp: '2026-04-15T10:54:48.982344'
  format: zmk-keymap-yaml
  version: '1.0'
keymapInfo:
  availableLayers: 0
  maxLayerNameLength: 20
  totalLayers: 4
layers:
- id: 0
  name: BASE
  bindings:
  - behavior_id: 3
    param1: 458793
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458782
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458783
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458784
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458785
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458786
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458787
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458788
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458789
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458790
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458791
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458794
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458795
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458772
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458778
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458760
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458773
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458775
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458780
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458776
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458764
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458770
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458771
    param2: 0
    behavior_name: kp
  - behavior_id: 9
    param1: 458797
    param2: 34013229
    behavior_name: mt
  - behavior_id: 3
    param1: 458977
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458756
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458774
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458759
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458761
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458762
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458763
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458765
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458766
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458767
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458803
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458836
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458976
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458781
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458779
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458758
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458777
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458757
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 786658
    param2: 0
    behavior_name: kp
  - behavior_id: 21
    param1: 0
    param2: 0
    behavior_name: rgb_ug
  - behavior_id: 3
    param1: 458769
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458768
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458806
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458807
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458808
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458792
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458979
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458978
    param2: 0
    behavior_name: kp
  - behavior_id: 7
    param1: 1
    param2: 0
    behavior_name: mo
  - behavior_id: 3
    param1: 458796
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458796
    param2: 0
    behavior_name: kp
  - behavior_id: 7
    param1: 2
    param2: 0
    behavior_name: mo
  - behavior_id: 3
    param1: 458804
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458828
    param2: 0
    behavior_name: kp
- id: 1
  name: NAV
  bindings:
  - behavior_id: 18
    param1: 0
    param2: 0
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 0
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 1
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 2
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 3
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 4
    behavior_name: bt
  - behavior_id: 3
    param1: 458816
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458817
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458818
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458819
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458820
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458821
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458810
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458811
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458812
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458813
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458814
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458815
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 3
    param1: 458826
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458834
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458829
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458827
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 6
    param1: 458809
    param2: 0
    behavior_name: kt
  - behavior_id: 3
    param1: 34013214
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013215
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013216
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013217
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013218
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 3
    param1: 458832
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458833
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458831
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458830
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 20
    param1: 1
    param2: 0
    behavior_name: ext_power
  - behavior_id: 20
    param1: 0
    param2: 0
    behavior_name: ext_power
  - behavior_id: 20
    param1: 2
    param2: 0
    behavior_name: ext_power
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 3
    param1: 458797
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013230
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013231
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013232
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013233
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
- id: 2
  name: SYM
  bindings:
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 3
    param1: 1074200606
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 1074200607
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 1074200608
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 1074200609
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 1074200610
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 1074200611
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 1074200612
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 3
    param1: 458805
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458782
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458783
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458784
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458785
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458786
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458787
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458788
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458789
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458790
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458791
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013233
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458810
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458811
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458812
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458813
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458814
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458815
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 3
    param1: 458797
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458798
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458799
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458800
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458801
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458816
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458817
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458818
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458819
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458820
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458821
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 3
    param1: 458803
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458804
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 34013236
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458806
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
- id: 3
  name: ADJUST
  bindings:
  - behavior_id: 18
    param1: 0
    param2: 0
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 0
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 1
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 2
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 3
    behavior_name: bt
  - behavior_id: 18
    param1: 3
    param2: 4
    behavior_name: bt
  - behavior_id: 3
    param1: 458810
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458811
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458812
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458813
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458814
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458822
    param2: 0
    behavior_name: kp
  - behavior_id: 20
    param1: 2
    param2: 0
    behavior_name: ext_power
  - behavior_id: 21
    param1: 4
    param2: 0
    behavior_name: rgb_ug
  - behavior_id: 21
    param1: 3
    param2: 0
    behavior_name: rgb_ug
  - behavior_id: 21
    param1: 6
    param2: 0
    behavior_name: rgb_ug
  - behavior_id: 21
    param1: 5
    param2: 0
    behavior_name: rgb_ug
  - behavior_id: 21
    param1: 11
    param2: 0
    behavior_name: rgb_ug
  - behavior_id: 3
    param1: 458815
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458816
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458817
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458818
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458819
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 21
    param1: 8
    param2: 0
    behavior_name: rgb_ug
  - behavior_id: 21
    param1: 7
    param2: 0
    behavior_name: rgb_ug
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 3
    param1: 458820
    param2: 0
    behavior_name: kp
  - behavior_id: 3
    param1: 458821
    param2: 0
    behavior_name: kp
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
  - behavior_id: 22
    param1: 0
    param2: 0
    behavior_name: trans
